# Generated by Django 5.0.1 on 2024-01-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudents',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudents',
            name='phone',
        ),
    ]
