# Generated by Django 5.0.1 on 2024-01-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_estudents_email_remove_estudents_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='DetailSale',
        ),
        migrations.DeleteModel(
            name='Estudents',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
