# Generated by Django 5.0.1 on 2024-01-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='code_student',
            new_name='cedula_estudiante',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='numero_identidad',
            new_name='cedula_representante',
        ),
    ]
