# Generated by Django 5.0.1 on 2024-01-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='user',
        ),
        migrations.AlterField(
            model_name='students',
            name='Representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='storeuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='students',
            name='ggroups',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_representative',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_secretary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_userstore',
        ),
        migrations.AddField(
            model_name='user',
            name='numero_identidad',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='Número de identidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
        migrations.DeleteModel(
            name='StoreUser',
        ),
    ]
