# Generated by Django 5.0.1 on 2024-01-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRepresentante',
            new_name='User',
        ),
    ]
