# Generated by Django 5.0.1 on 2024-01-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_userrepresentante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='students',
        ),
    ]
