# Generated by Django 5.0.1 on 2024-01-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_user_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(related_name='user_students', to='Users.estudents'),
        ),
    ]
