# Generated by Django 5.0.1 on 2024-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_students_representative_alter_students_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cedula_estudiante',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
