# Generated by Django 5.0.1 on 2024-02-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_students_cedula_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
    ]
