# Generated by Django 5.0.1 on 2024-01-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_user_students_user_students'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='estudents',
            managers=[
            ],
        ),
    ]
