# Generated by Django 5.0.1 on 2024-01-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_user_students_user_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='students',
        ),
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.estudents'),
        ),
    ]
