# Generated by Django 5.0.1 on 2024-01-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_user_students_user_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='students',
        ),
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='user_students', to='Users.estudents'),
        ),
    ]
