# Generated by Django 5.0.1 on 2024-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_remove_user_students_estudents_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_identidad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de identidad'),
        ),
    ]
