# Generated by Django 5.0.1 on 2024-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_user_numero_identidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_identidad',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de identidad'),
        ),
    ]
