# Generated by Django 5.0.1 on 2024-01-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_usersecretaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSecretaria',
        ),
    ]
