# Generated by Django 5.0.1 on 2024-01-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_rename_estudents_students'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Representative',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='code_students',
            new_name='cedula',
        ),
    ]
