# Generated by Django 5.0.1 on 2024-01-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_rename_user_representative_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Representative',
            new_name='User',
        ),
    ]
