# Generated by Django 5.0.1 on 2024-01-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listacompra',
            old_name='code_students',
            new_name='uid',
        ),
    ]
