# Generated by Django 5.0.1 on 2024-01-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
        ('products', '0005_remove_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping',
            new_name='OrdenCompra',
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={},
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='status',
            new_name='state',
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingDetail',
        ),
    ]
