# Generated by Django 5.0.1 on 2024-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0002_rename_code_students_listacompra_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacompra',
            name='id_shopping',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
