# Generated by Django 5.0.1 on 2024-02-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0003_alter_listacompra_id_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
