# Generated by Django 5.0.1 on 2024-01-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0003_itemordencompra_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordencompra',
            name='code',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='product_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buys.itemordencompra'),
        ),
    ]
