# Generated by Django 5.0.1 on 2024-01-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0005_remove_ordencompra_product_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='product_detail',
        ),
    ]
