# Generated by Django 5.0.1 on 2024-01-16 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0006_remove_ordencompra_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordencompra',
            name='orden_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='buys.ordencompra'),
        ),
    ]
