# Generated by Django 5.0.1 on 2024-01-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0007_itemordencompra_orden_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='state',
        ),
    ]
