# Generated by Django 5.0.1 on 2024-01-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0008_remove_ordencompra_state'),
        ('products', '0005_remove_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOrdenCompra',
            new_name='ItemCompra',
        ),
        migrations.RenameModel(
            old_name='OrdenCompra',
            new_name='ListaCompra',
        ),
    ]
